#!/usr/bin/env python
# encode:utf8
from tkinter import Tk, ttk
import subprocess
import sys
import datetime
import pyimgur
import tkinter.filedialog
import os

global url
global dirname
global dtename
global filename
global checkselect
url = 'https://api.imgur.com/3/upload'
dirname = "$HOME/Pictures/scs/"
datename = datetime.datetime.today()
filename = datename.strftime("%Y-%m-%d-%H:%M:%S")
# upload = filename
# Client ID
client = "74aefc9dcbd593d"
im = pyimgur.Imgur(client)


def ssArea(event):
    try:
        subprocess.run("mkdir -p dirname", shell=True)
        subprocess.check_output('gnome-screenshot -a -f %s%s.png' % (dirname, filename), shell=True)
    except:
        print("Error")
    return filename


def ssWindow(event):
    try:
        subprocess.run("mkdir -p $HOME/Pictures/scs", shell=True)
        subprocess.check_output('gnome-screenshot -w -d 5 -f %s%s.png' % (dirname, filename), shell=True)
    except:
        print("Error")
    return filename


def ssUpload(event):
    try:
        PATH = filename
        upimage = im.upload_image(PATH, title="scsUpload")
        print(upimage.link)
    except:
        print("Error")
    print("%s.png" % filename)
    # return lbl2.configure("UnSelected")


def ssSelect(event):
    home = os.environ['HOME']
    args = {
            "initialdir": "%s/Pictures/scs/" % home,
            "filetypes": [('画像ファイル', '*.png')]
            }
    filename = tkinter.filedialog.askopenfilename(**args)
    lbl2.configure(text="Selected")
    return filename


def ssQuit(event):
    sys.exit()


root = Tk()
root.title("SSTool")
lbl1 = ttk.Label(root, text="screenshot")
lbl2 = ttk.Label(root, text='UnSelect')
btn1 = ttk.Button(root, text='Area')
btn2 = ttk.Button(root, text='Window')
btn3 = ttk.Button(root, text='Select')
btn4 = ttk.Button(root, text='Upload')
btn10 = ttk.Button(root, text='Exit')
btn1.bind("<Button-1>", ssArea)
btn2.bind("<Button-1>", ssWindow)
btn3.bind("<Button-1>", ssSelect)
btn4.bind("<Button-1>", ssUpload)
btn10.bind("<Button-1>", ssQuit)
lbl1.grid()
btn1.grid()
btn2.grid()
lbl2.grid()
btn3.grid()
btn4.grid()
btn10.grid()
root.mainloop()
