#!/usr/bin/env python
# encode:utf8
from tkinter import Tk, ttk
import subprocess


def ssArea(event):
    try:
        area = subprocess.check_output('gnome-screenshot --area', shell=True)
    except:
        print("Error")
    print(area)


def ssWindow(event):
    try:
        wi = subprocess.check_output('gnome-screenshot -w --delay=5', shell=True)
    except:
        print("Error")
    print(wi)


root = Tk()
lbl1 = ttk.Label(root, text="screenshot")
btn1 = ttk.Button(root, text='Area')
btn2 = ttk.Button(root, text='Window')
btn1.bind("<Button-1>", ssArea)
btn2.bind("<Button-1>", ssWindow)
lbl1.grid()
btn1.grid()
btn2.grid()
root.mainloop()
